-- Migration 066: extend create_order_atomic to honor an initial_status
-- argument so OTC orders skip the documents step.
--
-- Why
-- ---
-- Until 2026-04-29 the legacy multi-step path AND the atomic RPC
-- (migration 049) hard-coded `order_status = 'AWAITING_DOCUMENTS'`
-- on every new order. That was always wrong for products with
-- `requires_prescription = false` (e.g. Vitamina D3) — the order
-- would land in AWAITING_DOCUMENTS, the order detail screen would
-- prompt the buyer for a prescription, and `getPrescriptionState`
-- would happily report `met = true` (since no item requires a
-- receipt) but no automatic transition existed to push it forward.
-- The buyer was stuck staring at a phantom upload prompt.
--
-- The TS layer (`services/orders.ts`) now computes
-- `initialStatus = hasRxProduct ? 'AWAITING_DOCUMENTS' : 'AWAITING_PAYMENT'`
-- and passes it to the RPC via `p_args.initial_status`. The default
-- (when the field is missing or empty) stays AWAITING_DOCUMENTS so
-- older callers / replays don't break.
--
-- Idempotent: CREATE OR REPLACE FUNCTION. Re-applying is a no-op
-- once the body matches.
--
-- LGPD: no PII change. Only changes which workflow lane an order
-- enters at creation time.

SET search_path TO public, extensions, pg_temp;

CREATE OR REPLACE FUNCTION public.create_order_atomic(
  p_args jsonb
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_order_id            uuid;
  v_order_code          text;
  v_order_total         numeric(10,2);
  v_buyer_type          text := p_args ->> 'buyer_type';
  v_clinic_id           uuid := NULLIF(p_args ->> 'clinic_id', '')::uuid;
  v_doctor_id           uuid := NULLIF(p_args ->> 'doctor_id', '')::uuid;
  v_delivery_address_id uuid := NULLIF(p_args ->> 'delivery_address_id', '')::uuid;
  v_pharmacy_id         uuid := NULLIF(p_args ->> 'pharmacy_id', '')::uuid;
  v_notes               text := NULLIF(p_args ->> 'notes', '');
  v_created_by          uuid := NULLIF(p_args ->> 'created_by_user_id', '')::uuid;
  v_estimated_total     numeric(10,2) := COALESCE((p_args ->> 'estimated_total')::numeric, 0);
  v_initial_status      text := COALESCE(NULLIF(p_args ->> 'initial_status', ''), 'AWAITING_DOCUMENTS');
  v_history_reason      text;
  v_items               jsonb := COALESCE(p_args -> 'items', '[]'::jsonb);
  v_item                jsonb;
BEGIN
  IF v_buyer_type NOT IN ('CLINIC', 'DOCTOR') THEN
    RAISE EXCEPTION 'invalid_buyer_type' USING ERRCODE = 'P0001';
  END IF;
  IF v_pharmacy_id IS NULL THEN
    RAISE EXCEPTION 'missing_pharmacy' USING ERRCODE = 'P0001';
  END IF;
  IF v_created_by IS NULL THEN
    RAISE EXCEPTION 'missing_actor' USING ERRCODE = 'P0001';
  END IF;
  IF jsonb_array_length(v_items) = 0 THEN
    RAISE EXCEPTION 'empty_items' USING ERRCODE = 'P0001';
  END IF;
  -- Reject anything outside the two allowed entry points so a typo
  -- in the caller can't slip an invalid status into the orders CHECK.
  IF v_initial_status NOT IN ('AWAITING_DOCUMENTS', 'AWAITING_PAYMENT') THEN
    RAISE EXCEPTION 'invalid_initial_status' USING ERRCODE = 'P0001';
  END IF;

  v_history_reason := CASE v_initial_status
    WHEN 'AWAITING_DOCUMENTS' THEN 'Pedido criado — aguardando receita'
    WHEN 'AWAITING_PAYMENT'   THEN 'Pedido criado — sem produtos sob receita'
    ELSE                           'Pedido criado'
  END;

  -- Insert order header (code is generated by trg_orders_generate_code).
  INSERT INTO public.orders (
    buyer_type, clinic_id, doctor_id, delivery_address_id, pharmacy_id,
    total_price, order_status, payment_status, transfer_status,
    notes, created_by_user_id, code
  ) VALUES (
    v_buyer_type,
    CASE WHEN v_buyer_type = 'CLINIC' THEN v_clinic_id ELSE NULL END,
    v_doctor_id,
    CASE WHEN v_buyer_type = 'DOCTOR' THEN v_delivery_address_id ELSE NULL END,
    v_pharmacy_id,
    v_estimated_total,
    v_initial_status,
    'PENDING',
    'NOT_READY',
    v_notes,
    v_created_by,
    ''
  )
  RETURNING id, code INTO v_order_id, v_order_code;

  FOR v_item IN SELECT * FROM jsonb_array_elements(v_items) LOOP
    INSERT INTO public.order_items (
      order_id, product_id, quantity, unit_price, total_price, coupon_id
    ) VALUES (
      v_order_id,
      (v_item ->> 'product_id')::uuid,
      (v_item ->> 'quantity')::int,
      COALESCE((v_item ->> 'unit_price')::numeric, 0),
      COALESCE((v_item ->> 'total_price')::numeric, 0),
      NULLIF(v_item ->> 'coupon_id', '')::uuid
    );
  END LOOP;

  INSERT INTO public.order_status_history (
    order_id, old_status, new_status, changed_by_user_id, reason
  ) VALUES (
    v_order_id, NULL, v_initial_status, v_created_by, v_history_reason
  );

  SELECT total_price INTO v_order_total
    FROM public.orders WHERE id = v_order_id;

  RETURN jsonb_build_object(
    'order_id', v_order_id,
    'order_code', v_order_code,
    'total_price', v_order_total
  );
END;
$$;

COMMENT ON FUNCTION public.create_order_atomic(jsonb) IS
  'Wave 7 — atomic order creation. Inserts orders + order_items + order_status_history in a single transaction. Pre-validation (RBAC, compliance, prescription rules) still lives in TS. Accepts optional p_args.initial_status (AWAITING_DOCUMENTS|AWAITING_PAYMENT) — default AWAITING_DOCUMENTS for back-compat. Raises P0001 with reason (invalid_buyer_type, missing_pharmacy, missing_actor, empty_items, invalid_initial_status).';

GRANT EXECUTE ON FUNCTION public.create_order_atomic(jsonb) TO service_role;

-- ── Smoke ─────────────────────────────────────────────────────────────────
DO $smoke$
DECLARE
  v_src text;
BEGIN
  SELECT prosrc INTO v_src
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
   WHERE n.nspname = 'public'
     AND p.proname = 'create_order_atomic';

  IF v_src IS NULL THEN
    RAISE EXCEPTION 'Migration 066 smoke: create_order_atomic missing';
  END IF;

  IF position('initial_status' IN v_src) = 0 THEN
    RAISE EXCEPTION 'Migration 066 smoke: initial_status not in body';
  END IF;

  IF position('invalid_initial_status' IN v_src) = 0 THEN
    RAISE EXCEPTION 'Migration 066 smoke: validation guard missing';
  END IF;

  RAISE NOTICE 'Migration 066 smoke passed';
END
$smoke$;
